services:
  - type: web
    name: bizzit-compfest
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install --only-binary=all --no-cache-dir -r requirements.txt
    startCommand: python bizzt_api.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: FLASK_ENV
        value: "production"
      - key: PIP_ONLY_BINARY
        value: ":all:"
